import Head from "next/head";
import BestGear from "../components/BestGear";
import CategoryLinks from "../components/CategoryLinks";
import Hero from "../components/Hero";
import ProductShowcase from "../components/ProductShowcase";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Audiophile E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <main className="mx-auto max-w-7xl px-6 pt-32 lg:px-16">
        <CategoryLinks />
        <ProductShowcase />
        <BestGear />
      </main>
    </div>
  );
}
